repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  # Frontend TypeScript and Vue.js checks
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript compilation check
        entry: bash -c 'cd frontend && npm run type-check'
        language: system
        files: ^frontend/.*\.(ts|tsx|vue)$
        pass_filenames: false

      - id: vue-lint
        name: Vue/TypeScript linting
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        files: ^frontend/.*\.(ts|tsx|vue|js|jsx)$
        pass_filenames: false

      - id: frontend-tests
        name: Frontend test validation
        entry: bash -c 'cd frontend && npm test -- --run'
        language: system
        files: ^frontend/.*\.(ts|tsx|vue|js|jsx)$
        pass_filenames: false
        # This hook ensures all tests pass before allowing commits
